# Q4 2024 Sales Data Cleaning & Analysis
### Pandas Data Analysis Project
This notebook focuses on cleaning a messy Q4 2024 e-commerce dataset and generating meaningful business insights using Pandas.

## Task 1: Load and Inspect the Data

In this step:
- We import required libraries (Pandas & NumPy)
- Create the DataFrame using the provided dataset
- Inspect structure and missing values

Understanding the dataset structure is essential before performing any cleaning operations.

In [3]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)

### Inspect Data Structure

We use `df.info()` to:
- Check column data types
- View non-null counts
- Understand missing values at a high level

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

### Check Missing Values

We use `df.isna().sum()` to:
- Count missing values in each column
- Identify which columns require cleaning

In [6]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

## Task 2: Handle Missing Values

Now we clean the dataset using appropriate strategies based on data type:

- Categorical columns → Fill with Mode
- Numerical columns → Fill with Mean or Median
- Time/Sequential data → Forward Fill
- Drop rows when necessary (payment_method)

This ensures the dataset is ready for analysis.

### Fill Missing Values in Categorical Columns

We fill missing values in:
- `region`
- `product_category`

Using the **mode (most frequent value)** because it preserves category distribution.

In [8]:
df['region'].fillna(df['region'].mode()[0],inplace=True)
df['product_category'].fillna(df['product_category'].mode()[0],inplace=True)

/tmp/ipykernel_415/1946799019.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product_category'].fillna(df['product_category'].mode()[0],inplace=True)

### Fill Missing Sales Amount

We replace missing values in `sales_amount` using the **median**.

Median is chosen because:
- It is robust to outliers
- It represents central tendency better for skewed sales data

In [9]:
df['sales_amount'].fillna(df['sales_amount'].median(),inplace=True)

/tmp/ipykernel_415/2381145706.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sales_amount'].fillna(df['sales_amount'].median(),inplace=True)

### Fill Missing Quantity using Forward Fill

Since transaction data is sequential,
we use **forward fill (ffill)** to propagate the last valid quantity value.

In [11]:
df['quantity'].fillna(method='ffill',inplace=True)

/tmp/ipykernel_415/2889277434.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['quantity'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_415/2889277434.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['quantity'].fillna(method='ffill',inplace=True)

### Fill Missing Customer Age

We replace missing values in `customer_age` using the **mean age**.
The result is rounded to maintain integer values.

In [13]:
df['customer_age'].fillna(round(df['customer_age'].mean()),inplace=True)
df['customer_age']=df['customer_age'].astype(int)

/tmp/ipykernel_415/3642806826.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_age'].fillna(round(df['customer_age'].mean()),inplace=True)

### Drop Rows with Missing Payment Method

Payment method is critical for transaction analysis.
Instead of guessing values, we remove rows where `payment_method` is missing.

In [14]:
df.dropna(subset=['payment_method'],inplace=True)

### Verify Data Cleaning

We confirm that no missing values remain in the dataset.
This ensures the dataset is clean and analysis-ready.

In [15]:
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            0
customer_age        0
payment_method      0
dtype: int64

## Task 3: GroupBy Analysis

Now that the dataset is clean, we perform aggregation analysis to generate business insights.

We analyze:
- Total sales by region
- Average sales by product category
- Region-product level performance

### Total Sales by Region

We group by `region` and calculate total sales.
This helps identify the highest revenue-generating region.

In [17]:
Total_Sales_Region=df.groupby('region')['sales_amount'].sum()
print(Total_Sales_Region)

region
East     3790.0
North    6460.0
South    1900.0
West     2230.0
Name: sales_amount, dtype: float64

### Average Sales by Product Category

We calculate the average sales for each product category
to understand category-level performance.

In [19]:
Average_Sales_Category=df.groupby('product_category')['sales_amount'].mean()
print(Average_Sales_Category)

product_category
Books           508.333333
Clothing        680.000000
Electronics    1381.250000
Home            812.500000
Name: sales_amount, dtype: float64

### Sales & Quantity by Region and Product Category

We perform multi-column grouping:
- region
- product_category

Then calculate:
- Total sales
- Total quantity

We use `reset_index()` to convert the hierarchical index into a flat table.

In [21]:
Grouped=df.groupby(['region','product_category'])[['sales_amount','quantity']].sum()
Grouped=Grouped.reset_index()
print(Grouped)

  region product_category  sales_amount  quantity
0   East            Books         800.0       4.0
1   East         Clothing         890.0       3.0
2   East      Electronics        2100.0       1.0
3  North         Clothing         510.0       3.0
4  North      Electronics        2700.0       3.0
5  North             Home        3250.0      12.0
6  South         Clothing        1900.0       9.0
7   West            Books         725.0       1.0
8   West         Clothing         780.0       5.0
9   West      Electronics         725.0       1.0

### Top 3 Region-Product Combinations

We sort the grouped results by sales_amount
and display the top 3 performing combinations.

In [22]:
Top_3=Grouped.sort_values('sales_amount',ascending=False).head(3)
print(Top_3)

  region product_category  sales_amount  quantity
5  North             Home        3250.0      12.0
4  North      Electronics        2700.0       3.0
2   East      Electronics        2100.0       1.0

## Task 4: Custom Aggregation

We create a custom function to calculate the sales range
(Maximum - Minimum sales).

This helps measure sales variability across regions.

### Sales Range by Region

We apply the custom function using `.agg()`
to calculate sales variation for each region.

In [23]:
def sales_range(x):
  return x.max() - x.min()

### Multiple Aggregations by Region

Using `.agg()` we calculate multiple metrics at once:

For `sales_amount`:
- Sum
- Mean
- Maximum

For `quantity`:
- Sum
- Minimum

This provides a complete performance summary per region.

In [25]:
Range_By_Region=df.groupby('region')['sales_amount'].agg(sales_range)
print(Range_By_Region)

region
East     1720.0
North     990.0
South     275.0
West       55.0
Name: sales_amount, dtype: float64

## Final Insights & Conclusion

- Identified top-performing regions based on total sales.
- Electronics category shows strong revenue performance.
- Certain region-product combinations significantly outperform others.
- Sales variation differs across regions.
- The dataset is now fully cleaned and ready for advanced analysis or visualization.

This structured cleaning and aggregation ensures reliable business insights.

In [28]:
Multiple_Metrics=df.groupby('region').agg({
    'sales_amount':['sum','mean','max'],
    'quantity':['sum','min']
})
print(Multiple_Metrics)

       sales_amount                     quantity
                sum        mean     max      sum  min
region
East         3790.0  947.500000  2100.0      8.0  1.0
North        6460.0  922.857143  1500.0     18.0  1.0
South        1900.0  633.333333   725.0      9.0  2.0
West         2230.0  743.333333   780.0      7.0  1.0